### ISSUE TITLE
Add ability to download file output snapshot of running jobs

### ISSUE THREAD

**Issue by fcasson** [prominence-eosc/prominence#80]
Or, even better (ask for the moon), to stream specific files or mount the running output directory  :-)

**Comment by alahiff** [comment]
The ability to see the contents of arbitrary files may actually be possible, will need to do some tests...

**Comment by fcasson** [comment]
This feature would bring more benefit for us than any other in the current issue list.

Alternatively, if there was prominence exec / condor_ssh_to_job it could solve this and any other issues I could think of for interacting with running jobs.

**Comment by alahiff** [comment]
@fcasson ok, I can probably start looking into this today.

**Comment by alahiff** [comment]
Have successfully got condor_ssh_to_job to work. Needed to add `openssh-clients` to the PROMINENCE machine running HTCondor, and `openssh-server` to the worker.

Next steps:
- [ ] Add exec route to the REST API for running a single command in the job
- [ ] Add `exec` command to the CLI

Note that `prominence exec` will just run a single command and return any standard output/error. Getting `prominence exec` to open up a shell which the user can type commands into is more difficult.

**Comment by alahiff** [comment]
Update to REST API tracked in https://github.com/prominence-eosc/prominence/issues/93

**Comment by alahiff** [comment]
Update to CLI tracked in https://github.com/prominence-eosc/cli/issues/9

**Comment by alahiff** [comment]
REST API updates implemented in https://github.com/prominence-eosc/prominence/commit/33e0d5cf6e997493c968e92a7103e91e5ced3416 https://github.com/prominence-eosc/prominence/commit/dcb7549c9cb956a809d9fc31cfb812254a5d91d1 https://github.com/prominence-eosc/prominence/commit/fff9c945deea5c03caba32a8b4e3537ba42fdf7b https://github.com/prominence-eosc/prominence/commit/c03cd04707817b92f97d6c11c078045c3119d6db https://github.com/prominence-eosc/prominence/commit/f63678d52b67913ccc74a3374a85ca744d36e62e https://github.com/prominence-eosc/prominence/commit/3a34988483941f37e098a43b7d22e93c1cef2f6f https://github.com/prominence-eosc/prominence/commit/f1261137dcd008ba8e786e70a11985f3aa9490b1

**Comment by alahiff** [comment]
@fcasson with the CLI 0.1.24 or above you can use `prominence exec`. Note that this is not really suitable for downloading large files but is useful for checking if a job is working correctly or not. I'll still consider other options to allow access to large output files if necessary.

**Comment by fcasson** [comment]
Actually can you clarify how one would use prominence exec to download a file?

**Comment by alahiff** [comment]
It's not really a mechanism for downloading files - it's meant to help with checking the status of a job and/or debugging etc, e.g. tail an output file or log file to see if things look sensible, do a "ps" to see what processes are running, do an "ls" to see what files have been generated, ...

To look at an output file, for a JINTRAC job you could do something like:
```
prominence exec <job id> "cat /work/<filename>"
```
and the contents of the file would appear in stdout, just like if you'd run `cat` locally.

Or for https://github.com/prominence-eosc/prominence/issues/81 (i.e. stopping a job by creating a special file) you could do this:
```
prominence exec <job id> "touch /work/<special filename>"
```

Maybe this isn't quite what you want...

Alternatives:
1. `prominence snapshot`? Specify a file and it will be uploaded to ECHO then downloaded locally. Would setup a short lifetime on such files in ECHO (e.g. they're deleted automatically after 1 day or even less). I think I know how to do most of this, but it's not implemented.

2. There are options to mount volumes from B2DROP (https://b2drop.eudat.eu) or OneData (https://onedata.org). in this case in real time you could look at what your job is doing (in terms of files being written), e.g. in a web browser or on your desktop/laptop. The file read/write performance would be reduced, but this may not be a problem. The main problem with this is that we only have 20 GB each on B2DROP (everyone gets 20 GB) and we don't have access to OneData storage. This may change in future, but not in the short/medium term.

I get the impression ideally you want someting like 2 above.

**Comment by fcasson** [comment]
Hi Andrew

Yes, prominence exec is perfect for debugging and stopping the job.  I think we can probably even use it for catting individual binary files and piping into a local file (but this is a bit inelegant).

For snapshots, either 1. or 2. is possible - Not individual files really, but the whole run directory. Without thinking carefully about pros and cons, I like 1., because it is simple and generates no extra dependences for mounting / examining our data.  Our rundirs (for jetto at least) are smallish (as you can see from the completed jobs) so I don't think the disk space is a big issue, and for us it would be fine to overwrite the previous snapshot.

**Comment by alahiff** [comment]
The simplest (& fastest) would be 1. with the assumption that there is only ever one snapshot, i.e. if you create a new snapshot any existing snapshots are overwritten (this means I only need to create & pass a single pre-signed PUT URL to each job to be used for uploading any potential snapshots to ECHO).

Probably something like:
```
prominence snapshot /work
```
so that users can pick what is snapshotted (in order to make it useful more generally).

**Comment by fcasson** [comment]
The simple and fast option meets our need.

**Comment by alahiff** [comment]
Now implementend, both in the server and CLI. Users will need to update the CLI to the latest version (0.2.0).

Example usage:
```
$ prominence snapshot 25374 /work
Downloading file "snapshot.tgz"
[==================================================]
```
Note that the snapshot tarball is always called `snapshot.tgz`.

You can specify a file or directory when running `prominence snapshot`, and in each case a tarball called `snapshot.tgz` is created. 

FYI the tarball is created from outside the container, but if you specify an absolute path (e.g. `work` above) it will be mapped to the appropriate path where appropriate. Random absolute paths (e.g. `/`, `/usr/local`, ...) will give an error.

Note that from the CLI you currently create a snapshot and download it at the same time, but this corresponds to 3 REST API requests:
* PUT to the PROMINENCE API to create the snapshot
* GET to the PROMINENCE API to get the URL to the snapshot
* GET to ECHO, using the previously obtained URL

So if necessary it's possible to create a snapshot and download it later. Currently snapshots have a lifetime of 2 days.

**Comment by fcasson** [comment]
Thanks!  This feature works perfectly and is a gamechanger for JINTRAC.
